# Generated by Django 3.2.16 on 2022-12-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='PortfolioComments',
        ),
        migrations.RenameModel(
            old_name='Frameworks',
            new_name='PortfolioDatabases',
        ),
        migrations.RenameModel(
            old_name='Databases',
            new_name='PortfolioFrameworks',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='PortfolioLanguages',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='PortfolioProjects',
        ),
        migrations.RenameModel(
            old_name='Tools',
            new_name='PortfolioTools',
        ),
        migrations.AlterModelOptions(
            name='portfoliocomments',
            options={'verbose_name_plural': 'PortfolioComments'},
        ),
        migrations.AlterModelOptions(
            name='portfoliodatabases',
            options={'verbose_name_plural': 'PortfolioDatabases'},
        ),
        migrations.AlterModelOptions(
            name='portfolioframeworks',
            options={'verbose_name_plural': 'PortfolioFrameworks'},
        ),
        migrations.AlterModelOptions(
            name='portfoliolanguages',
            options={'verbose_name_plural': 'PortfolioLanguages'},
        ),
        migrations.AlterModelOptions(
            name='portfolioprojects',
            options={'verbose_name_plural': 'PortfolioProjects'},
        ),
        migrations.AlterModelOptions(
            name='portfoliotools',
            options={'verbose_name_plural': 'PortfolioTools'},
        ),
        migrations.RenameField(
            model_name='portfoliodatabases',
            old_name='framework',
            new_name='database',
        ),
        migrations.RenameField(
            model_name='portfolioframeworks',
            old_name='database',
            new_name='framework',
        ),
    ]
